name: objectbox_generator
description: ObjectBox Flutter / Dart database binding code generator - finds annotated entities and adds them to the ObjectBox DB model.
# Link to actual directory in repository so file links on pub.dev work.
repository: https://github.com/objectbox/objectbox-dart/tree/main/generator
homepage: https://objectbox.io
version: 2.5.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  objectbox: 
    git:
      url: https://github.com/posbankbh/objectbox-dart.git
      path: 'objectbox'
  analyzer: '>=5.2.0 <7.0.0' # 5.1.0 has a bug where DartType.element has been removed.
  build: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  path: ^1.8.0
  source_gen: ^1.0.0
  pubspec_parse: ^1.0.0
  yaml: ^3.0.0
  http: '>=0.13.5 <2.0.0'
  cryptography: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.16.5
  # lints 2.1.0+ requires Dart 3, but CI still tests with Dart 2, but also need 3.0.0+ to match pana
  lints: '>=2.0.1 <4.0.0'
  crypto: ^3.0.2
  pub_semver: ^2.1.3
  package_config: ^2.1.0
